[package]
name = "demo_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
NOSHP-Client = "0.3.3"
clap = { version = "4.5.4", features = ["derive"] }
soloud = "1.0.5"
